### ISSUE TITLE
请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字

### ISSUE THREAD

**Issue by bailanguanjun** [tyql688/WutheringWavesUID#12]
请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字

**Comment by tyql688** [comment]
> 请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字

腾子弄的吧，咱也不清楚~

**Comment by bailanguanjun** [comment]
> > 请问一下为什么使用QQ官方机器人部署后，每个用户的ID不是QQ号，而是一串十六进制数字
> 
> 腾子弄的吧，咱也不清楚~

嗯 就是腾子弄的 前面看了文档
![微信图片_20241205205236](https://github.com/user-attachments/assets/96c5cec5-c856-47d4-be0a-b6175181db84)

**Comment by bailanguanjun** [comment]
> > 请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字
> 
> 腾子弄的吧，咱也不清楚~

佬 Moealkyne的攻略，在折枝之前都是多图，用ww角色攻略[]查找之前的攻略会回答“[鸣潮] 该角色攻略不存在, 请检查输入角色是否正确！”，请问这个该怎么解决

**Comment by bailanguanjun** [comment]
> > > 请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字
> > 
> > 
> > 腾子弄的吧，咱也不清楚~
> 
> 佬 Moealkyne的攻略，在折枝之前都是多图，用ww角色攻略[]查找之前的攻略会回答“[鸣潮] 该角色攻略不存在, 请检查输入角色是否正确！”，请问这个该怎么解决

或者能否将这些攻略保存在本地，这样每次响应速度应该能快一点

**Comment by tyql688** [comment]
> > > > 请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字
> > > 
> > > 
> > > 腾子弄的吧，咱也不清楚~
> > 
> > 
> > 佬 Moealkyne的攻略，在折枝之前都是多图，用ww角色攻略[]查找之前的攻略会回答“[鸣潮] 该角色攻略不存在, 请检查输入角色是否正确！”，请问这个该怎么解决
> 
> 或者能否将这些攻略保存在本地，这样每次响应速度应该能快一点

下次可以直接开新issue哈~

最新的攻略逻辑就是变成我来维护了，可能你好久没更新了

然后控制台可以设置选择角色攻略作者，也可以选择all

**Comment by bailanguanjun** [comment]
> > > > > 请问一下为什么使用QQ官方机器人部署后每个用户的ID不是QQ号而是一串十六进制数字
> > > > 
> > > > 
> > > > 腾子弄的吧，咱也不清楚~
> > > 
> > > 
> > > 佬 Moealkyne的攻略，在折枝之前都是多图，用ww角色攻略[]查找之前的攻略会回答“[鸣潮] 该角色攻略不存在, 请检查输入角色是否正确！”，请问这个该怎么解决
> > 
> > 
> > 或者能否将这些攻略保存在本地，这样每次响应速度应该能快一点
> 
> 下次可以直接开新issue哈~
> 
> 最新的攻略逻辑就是变成我来维护了，可能你好久没更新了
> 
> 然后控制台可以设置选择角色攻略作者，也可以选择all

更新了 大佬太猛辣！
