### ISSUE TITLE
网页控制台中的全部开启签到似乎没有起到作用

### ISSUE THREAD

**Issue by lilinxuan1999** [tyql688/WutheringWavesUID#13]
我的登录用户有六百多人，但是私聊给我的反馈只有一百多人进行签到

**Comment by lilinxuan1999** [comment]
![Screenshot_2024-12-30-01-50-54-182_com.tencent.mobileqq.png](https://github.com/user-attachments/assets/74e51613-2bd0-4ed3-b557-6eff03ef5c65)

这个功能好像只短暂出现过几天？现在进行全部签到后就没有再给主人私信推送过了。

**Comment by tyql688** [comment]
加群反馈吧
76436110
