### ISSUE TITLE
有办法清理掉bot已经退了的群的自动签到吗

### ISSUE THREAD

**Issue by lniuua** [tyql688/WutheringWavesUID#16]
签到越来越多了，在控制台的绑定管理里删除掉有没有用呢
![图片](https://github.com/user-attachments/assets/7c603c20-5c97-4ab7-a849-0cbdeaee1d64)

**Comment by tyql688** [comment]
`
UPDATE WavesUser
SET sign_switch = 'off'
WHERE sign_switch = '群号';
`

`
DELETE WavesUser
WHERE sign_switch = '群号';
`

后面写个指令吧 但是前提得知道群号。

**Comment by lniuua** [comment]
感谢大佬

**Comment by tyql688** [comment]
> 感谢大佬

命令已加-> **ww删除自动签到**
