### ISSUE TITLE
【🚩 功能建议征集】

### ISSUE THREAD

**Issue by tyql688** [tyql688/WutheringWavesUID#3]
![h20hrluaynk](https://github.com/user-attachments/assets/d729816d-afea-49bf-94e4-27372138cbee)

**Comment by YashajinAlice** [comment]
請問國際服是否也可以實現呢？因為目前經過爬文，頂多可以實現卡池查詢而已。
不管是serverid或uid什麼的，但不管怎麼找，國際服似乎沒辦法用一般的方法檢視到token

**Comment by tyql688** [comment]
> 請問國際服是否也可以實現呢？因為目前經過爬文，頂多可以實現卡池查詢而已。 不管是serverid或uid什麼的，但不管怎麼找，國際服似乎沒辦法用一般的方法檢視到token

当前，wwuid完全基于库街区平台。对于国际服，库洛暂时未提供登录或账号绑定服务，也没有推出针对国际服的库街区版本。不过，如果库洛未来决定推出海外版社区，wwuid将会及时更新并提供支持。

**Comment by YashajinAlice** [comment]
> > 請問國際服是否也可以實現呢？因為目前經過爬文，頂多可以實現卡池查詢而已。 不管是serverid或uid什麼的，但不管怎麼找，國際服似乎沒辦法用一般的方法檢視到token
> 
> 当前，wwuid完全基于库街区平台。对于国际服，库洛暂时未提供登录或账号绑定服务，也没有推出针对国际服的库街区版本。不过，如果库洛未来决定推出海外版社区，wwuid将会及时更新并提供支持。

理解，所以依照目前國際服僅可以實現分析卡池的部分而已www有點難過XD不過也感謝回應！

**Comment by jinglu0** [comment]
> 请问可否实现通过UID查询别人的面板呢？比如"ww椿面板123456789"

更新试试 窥视(:

**Comment by Alice-wind** [comment]
已更新，感谢作者

**Comment by Alice-wind** [comment]
有一个问题，登录后什么情况下会失效？我这边昨天到今天登录了大概300+用户，但是现在我看gscore控制台中的“用户管理”里大部分都显示失效，实际上也有很多用户反应登录后过段时间就会自己失效

**Comment by tyql688** [comment]
> 有一个问题，登录后什么情况下会失效？我这边昨天到今天登录了大概300+用户，但是现在我看gscore控制台中的“用户管理”里大部分都显示失效，实际上也有很多用户反应登录后过段时间就会自己失效

我也发现了 今天改了个刷新逻辑 本来是为了给不登录用户做的刷新，但是影响了登录用户。改回去了 更新下

**Comment by tyql688** [comment]
> 有一个问题，登录后什么情况下会失效？我这边昨天到今天登录了大概300+用户，但是现在我看gscore控制台中的“用户管理”里大部分都显示失效，实际上也有很多用户反应登录后过段时间就会自己失效

如果库洛没改逻辑 登录后应该很长一段时间都不失效的。

**Comment by lilinxuan1999** [comment]
突然发现没有活动日历功能，请问是否考虑建议增加日历功能(就是库街区里wiki板块里面那个版本活动，如果有时间轴能看到卡池倒计时和深渊持续时间就更好啦)

**Comment by lilinxuan1999** [comment]
突然发现没有活动日历功能，请问是否考虑建议增加日历功能(就是库街区里wiki板块里面那个版本活动，如果有时间轴能看到卡池倒计时和深渊持续时间就更好啦)

**Comment by tyql688** [comment]
> 突然发现没有活动日历功能，请问是否考虑建议增加日历功能(就是库街区里wiki板块里面那个版本活动，如果有时间轴能看到卡池倒计时和深渊持续时间就更好啦)

可以加，就是目前没有特别准的日历，wiki的日历有点偏差。我先记着（：

**Comment by lilinxuan1999** [comment]
刷新功能似乎并没有刷新面板，早上换的声骸，直到下午都没有刷新

**Comment by tyql688** [comment]
> 刷新功能似乎并没有刷新面板，早上换的声骸，直到下午都没有刷新

只绑定uid的用户，需要在库街区点开鸣潮数据卡片自行进行数据刷新，然后再发送【ww刷新面板】指令才可刷新。
登录的用户或者绑定token的用户，面板数据是可以直接同步库街区更新的，发送【ww刷新面板】指令为最新的库街区数据。

原因是，绑定uid的用户用的是全局token（登录的或者是已绑定token的用户），频繁使用他们的token进行刷新面板会导致他们的token失效（：。

解决办法：
1.登录后使用自己的token查询
2.自行去库街区刷新

（：

**Comment by lilinxuan1999** [comment]
希望能有自定义面板图的功能 ww上传xx面板图

**Comment by tyql688** [comment]
> 希望能有自定义面板图的功能 ww上传xx面板图

已排期～

**Comment by lniuua** [comment]
建议没有绑定ck的不进入排行，还有就是角色攻略前缀太长了，建议改成ww椿攻略

**Comment by lilinxuan1999** [comment]
> 建议没有绑定ck的不进入排行，还有就是角色攻略前缀太长了，建议改成ww椿攻略

还有类似 ww深渊超载区 这种命令 可以直接改成ww超载区 也能触发

**Comment by tyql688** [comment]
> 攻略

后续会在控制台加个开关，只有绑定token的用户会进排行。bot主人可以控制开关～

命令优化也在排期中～

感谢建议

**Comment by lilinxuan1999** [comment]
你好，目前抽卡分析似乎只能私聊使用，如果这一点不改的话，建议如果在群聊使用相关命令的时候则提示用户前往私聊使用或者更新也可以在群聊中使用

**Comment by lniuua** [comment]
建议将查看uid\切换uid这些功能也做成图片形式,像云崽的喵喵插件那样,token有效的就显示已登录,如果开启了自动签到，体力推送等功能也可以显示在上面。

**Comment by lilinxuan1999** [comment]
更新插件 WutheringWavesUID 中...

执行 git fetch 失败, 请检查控制台...

请问输入命令更新时出现这种报错应该怎么解决

**Comment by xinxiuzhu** [comment]
能否结合wiki给出一些养成推荐呢🤝

**Comment by tyql688** [comment]
> 能否结合wiki给出一些养成推荐呢🤝

这个暂时不会做

**Comment by tyql688** [comment]
> 建议将查看uid\切换uid这些功能也做成图片形式,像云崽的喵喵插件那样,token有效的就显示已登录,如果开启了自动签到，体力推送等功能也可以显示在上面。

可能会考虑后续优化

**Comment by xinxiuzhu** [comment]
> > 能否结合wiki给出一些养成推荐呢🤝
> 
> 这个暂时不会做

好的，另外那个声骸评分面板，能不能优化一下，显示一个上限值，比如说暴击 9.6% /10.5%之类的？谢谢

**Comment by tyql688** [comment]
> > > 能否结合wiki给出一些养成推荐呢🤝
> > 
> > 
> > 这个暂时不会做
> 
> 好的，另外那个声骸评分面板，能不能优化一下，显示一个上限值，比如说暴击 9.6% /10.5%之类的？谢谢

有点没地方了

**Comment by tyql688** [comment]
> 希望能有自定义面板图的功能 ww上传xx面板图

已上线~

**Comment by tyql688** [comment]
> > > 希望能有自定义面板图的功能 ww上传xx面板图
> > 
> > 
> > 已上线~
> 
> 感谢，辛苦。顺便问一句。暗主的性别是怎么指定的

ww上传暗主男面板图

ww上传光主女面板图

（这样

**Comment by seikeng** [comment]
请问导入抽卡记录能否导入以前导出的文件？抽卡链接现在只保留半年记录了。

**Comment by tyql688** [comment]
> 请问导入抽卡记录能否导入以前导出的文件？抽卡链接现在只保留半年记录了。



请在这条issue下回复；请勿在close的issue下回复
https://github.com/tyql688/WutheringWavesUID/issues/20

1.什么软件导出的？
2.什么导出格式？
3.请给予示例
