### ISSUE TITLE
使用ww深渊无反应

### ISSUE THREAD

**Issue by AyasakiAtre** [tyql688/WutheringWavesUID#4]
10-14 12:06:29 [INFO] gsuid_core.handler | [Raw] raw_text=ww深渊, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=**, msg_id=1423918820, user_type=group, group_id=**, user_id=**, user_pm=0, content=[Message(type='text', data='ww深渊')],  
 10-14 12:06:29 [INFO] gsuid_core.handler | [Trigger] 消息 「ww深渊」 触发 「command」 类型触发器, 关键词: 「ww深渊」  
 10-14 12:06:29 [INFO] gsuid_core.handler | [Command] command=ww深渊, text= 
 Task exception was never retrieved
future: <Task finished name='Task-7339' coro=<send_waves_abyss_info() done, defined at /root/gsuid_core/gsuid_core/sv.py:34> exception=TypeError('plugins.WutheringWavesUID.WutheringWavesUID.utils.api.model.AccountBaseInfo() argument after ** must be a mapping, not str')>
Traceback (most recent call last):
  File "/root/gsuid_core/gsuid_core/sv.py", line 37, in wrapper
    result = await func(bot, event)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gsuid_core/gsuid_core/plugins/WutheringWavesUID/WutheringWavesUID/wutheringwaves_abyss/__init__.py", line 34, in send_waves_abyss_info
    im = await draw_abyss_img(ev, uid)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gsuid_core/gsuid_core/plugins/WutheringWavesUID/WutheringWavesUID/wutheringwaves_abyss/draw_abyss_card.py", line 69, in draw_abyss_img
    account_info = AccountBaseInfo(**account_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: plugins.WutheringWavesUID.WutheringWavesUID.utils.api.model.AccountBaseInfo() argument after ** must be a mapping, not str

**Comment by tyql688** [comment]
更新 已修复
