### ISSUE TITLE
插件载入失败

### ISSUE THREAD

**Issue by MoonStarrySky** [tyql688/WutheringWavesUID#5]
![image](https://github.com/user-attachments/assets/208f4b00-39f9-40af-b8d1-e7436a596de2)
![image](https://github.com/user-attachments/assets/afb0997c-e66e-4b6b-b57f-f4bed73d59ae)

**Comment by tyql688** [comment]
依赖pycryptodome
请自行安装 
poetry run pip install pycryptodome 
or 
pdm run pip install pycryptodome

可以先这样处理，后续我会把加密解密去掉

**Comment by tyql688** [comment]
已删除pycryptodome依赖
