### ISSUE TITLE
yunzai的ws插件地址和gscore配置的一致，为什么连接不上。

### ISSUE THREAD

**Issue by MoonStarrySky** [tyql688/WutheringWavesUID#6]
![image](https://github.com/user-attachments/assets/274250f4-d2f6-45b6-97e9-8c1fd3e6b3ae)
![image](https://github.com/user-attachments/assets/c6de2f60-960b-4263-b340-4490d8913cf6)
![image](https://github.com/user-attachments/assets/34990ef3-12aa-416e-8ab7-77adb898ed1d)
，我不太确定有没有问题，大佬帮我看看什么问题，为什么连接不上。

**Comment by tyql688** [comment]
![image](https://github.com/user-attachments/assets/97cf873f-dcac-480d-b9ca-038f70fa8215)
看了下ws的代码，这里连接的地址应该是ws格式的。
