### ISSUE TITLE
關於支援的平台Discord

### ISSUE THREAD

**Issue by YashajinAlice** [tyql688/WutheringWavesUID#9]
我從GsCore下安裝了WWUID，看說明是有支援discord，我該如何設置？？

**Comment by tyql688** [comment]
可以尝试使用nb适配器的discard
https://nonebot.dev/store/adapters

> 我從GsCore下安裝了WWUID，看說明是有支援discord，我該如何設置？？

**Comment by YashajinAlice** [comment]
> 可以尝试使用nb适配器的discard https://nonebot.dev/store/adapters
> 
> > 我從GsCore下安裝了WWUID，看說明是有支援discord，我該如何設置？？

有看過，只是安裝教程實在是看不太懂，core安裝在nb根目錄上級，那我從core上下載的wwuid怎麼關聯到nb上
.env檔上好像也要自己加 token之類的 QAQ 我嘗試了幾次吧，都沒辦法（笑死

**Comment by tyql688** [comment]
> > 可以尝试使用nb适配器的discard https://nonebot.dev/store/adapters
> > > 我從GsCore下安裝了WWUID，看說明是有支援discord，我該如何設置？？
> 
> 有看過，只是安裝教程實在是看不太懂，core安裝在nb根目錄上級，那我從core上下載的wwuid怎麼關聯到nb上 .env檔上好像也要自己加 token之類的 QAQ 我嘗試了幾次吧，都沒辦法（笑死

可能需要你自行研究了 （

**Comment by YashajinAlice** [comment]
不好意思在关闭版中回复，我已完成安装机器人也成功运行不过指令的部分该如何发送？

**Comment by YashajinAlice** [comment]
> > 不好意思在关闭版中回复，我已完成安装机器人也成功运行不过指令的部分该如何发送？
> 
> `ww帮助` ?

没有反应，机器人有成功上线，不过输入指令时无反应（我给个.env.prod){none.bot}
WW插件放置none的src/plugins

`ENVIRONMENT=prod
DRIVER=~fastapi+~httpx+~websockets
DISCORD_BOTS='
[
  {
    "token": "--",
    "intent": {
      "guild_messages": true,
      "direct_messages": true
    },
    "application_commands": {"*": ["*"]}
  }
]
'
`
